version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: docker_fast_server
    command: sh -c 'python fastapi-server.py';
    ports:
      - "8888:8888"
  test_server:
    build:
      context: .
      dockerfile: docker_fast_test
    command: sh -c 'python test-fastapi.py';
    depends_on:
      - server